version: '3'

services: 
    web:
        build: .
        # command: python /code/manage.py runserver 0.0.0.0:3000
        command: gunicorn shivent.wsgi -b 0.0.0.0:3000
        env_file: 
            - .env
        volumes: 
            - .:/code
        ports: 
            - 3000:3000
        depends_on: 
            - db
    
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - .env
    
volumes: 
    postgres_data: