version: '3'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:3000
        environment: 
            - SECRET_KEY=sw4xfmk!ck=0i4t-1=2g&^)3p*%%-ps)6h!l&ifsu9lhcl4-d5
            - DEBUG=1
        volumes: 
            - .:/code
        ports: 
            - 3000:3000
        depends_on: 
            - db
    
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=shiventuser
            - POSTGRES_PASSWORD=shifatech20
            - POSTGRES_DB=shivent
    
volumes: 
    postgres_data: